---
title: "Enough is enough: How to sample plant-pollinator networks to make relative comparisons"
author: "I. Bartomeus, et al..."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

Characterising complex networks on interacting species is challenging. Two major stumbling blocks are a) correctly identifying species identity and b) having a sufficient sampling size for detecting all occurring links. A revisión of recently published plant-pollinator networks shows that most published networks group several species into morphospecies or even work at the genus level. In addition, when evaluated, sampling completness is never reached. This has clear implications for describing the network structure, but it is unknown how it affects relative comparisions among networks. Ecologists are often more interested in the relative comparision among communities with contrasting environments or treatments rather than in the absolute values. When two networks are sampled using the same methods, low taxonomic resolution and limited sampling effort may not change its relative comparision, but this has never been tested empirically. I use an intensive sampling of 16 fully resolved plant-pollinator networks acorss an environmental gradient to compare if the relative ranking of the main network propierties changes when increasing taxonomic resolution (from morphospecies tos species) and sampling effort. Then, I tested to which degree recently developed techniques for predicting missing links enhance the relative coparisions of poorly sampled networks. Determining which methods and indexes are robust to relative comparisions is needed in order to empirically test for pressing environmental changes that interacting communities are facing.

#Key papers and random notes:

-sampling completness: Chacoff, Nilsen, Bartomeus

-comparision metric: Saaverda preprint.