---
title: "Quantitative analysis"
author: "Nestor & Paco"
date: "27 June 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r}
intdata <- read.csv("data/interactions_clean.csv", header = TRUE)

```


## calculate metrics

```{r}
calculate_metrics <- function(df = intdata, treatment = "transects", taxores = NULL) {
    
    
        if (treatment == "transects") df <- subset(df, df$Out == "transect")
        if (treatment == "transfocal") df <- subset(df, df$Out == "transect" | df$Out == "focal")
        if (treatment == "all") df = df
        
        
        if (!is.null(taxores)) {
        
        if (treatment != "transects") stop("For analyses with taxonomic resolution, treatment must be = transects")
    }
    
   
    sites <- unique(df$Site_ID)
    ntw_m <- data.frame(site = sites, connectance = NA, links_per_species = NA,
                        nestedness = NA, H2 = NA, weightedNODF = NA,
                        interaction_evenness = NA)
    for (i in 1:length(sites)) {
        temp <- subset(df, Site_ID == sites[i])
        temp <- droplevels(temp)
        
        if (is.null(taxores)) {
            form <- as.formula("Plant_gen_sp ~ Pollinator_gen_sp")
        } else {
            form <- as.formula(paste0("Plant_gen_sp ~ ", taxores))
        }
        web <- reshape2::dcast(temp, form, fun.aggregate = sum, value.var = "Frequency")
        rownames(web) <- web$Plant_gen_sp
        web <- web[,-1]
        ntw_m[i,2:7] <- bipartite::networklevel(web = web, index = c("connectance", "links per species", "nestedness", "H2", "weighted NODF", "interaction evenness"))
        
        ## insert here null model stuff
    }
    
    ntw_m$treatment <- treatment
    
    if (!is.null(taxores)) ntw_m$taxores <- taxores
    
    ntw_m
    
}


metrics <- c("connectance", "links_per_species", "nestedness", "H2", 
             "weightedNODF", "interaction_evenness")
```


## ANALYSIS OF SAMPLING METHOD

```{r}
transects <- calculate_metrics(intdata, treatment = "transects")
transects.focal <- calculate_metrics(intdata, treatment = "transfocal")
all <- calculate_metrics(intdata, treatment = "all")

sampling.comparison <- dplyr::bind_rows(transects, transects.focal, all)
sampling.comparison$treatment <- factor(sampling.comparison$treatment,
                               levels = c("transects", "transfocal", "all"))
levels(sampling.comparison$treatment) <- c("Transects", "TransFocal", "TransFocalObs")
```


## ANALYSIS OF TAXONOMIC RESOLUTION

```{r}
genus <- calculate_metrics(intdata, treatment = "transects", taxores = "Pollinator_genus")
genus.sp <- calculate_metrics(intdata, treatment = "transects", taxores = "Pollinator_gen_sp")
morphosp <- calculate_metrics(intdata, treatment = "transects", taxores = "Morphospecie2")

taxa.comparison <- dplyr::bind_rows(genus, genus.sp, morphosp)
taxa.comparison$taxores <- factor(taxa.comparison$taxores,
                               levels = c("Pollinator_genus", 
                                          "Morphospecie2", 
                                          "Pollinator_gen_sp"))
levels(taxa.comparison$taxores) <- c("Genus", "Morphospecies", "Species")
```


## DATAVIZ

```{r}
library(ggplot2)

plot_comparison <- function(metric, taxa = FALSE, df) {
    
    if (isTRUE(taxa)) {
        xvar <- "taxores"
        lab <- "Taxonomic resolution"
    } else {
        xvar = "treatment"
        lab = "Sampling method"
    }
    
    p <- ggplot(df, aes(group = site, colour = site)) +
        aes_string(x = xvar, y = metric) +
        geom_line() +
        geom_point() +
        labs(x = lab) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
        scale_colour_discrete() # change  
    
    print(p)
    
}
```


```{r}
sampling.plots <- lapply(metrics, plot_comparison, taxa = FALSE, df = sampling.comparison)
```


```{r}
taxa.plots <- lapply(metrics, plot_comparison, taxa = TRUE, df = taxa.comparison)
```


## COMPARE APPROACHES

### Sampling method

```{r}
library(reshape2)

compare_methods <- function(metric, df, taxa = FALSE) {
    
    if (isTRUE(taxa)) {
        best <- "Species"
        form <- as.formula("site ~ taxores")
    } else {
        best <- "TransFocalObs"
        form <- as.formula("site ~ treatment")
    }
    
    
    df2 <- reshape2::dcast(df, form, value.var = metric)
    require(ggplot2)
    
    ggfun <- function(df = df2, respo = best, xvar, metrica = metric) {
        p1 <- ggplot(df, aes(colour = site)) + 
        aes_string(y = best, x = xvar) +
        xlim(min(df[[xvar]], df[[respo]]), max(df[[xvar]], df[[respo]])) +
        ylim(min(df[[xvar]], df[[respo]]), max(df[[xvar]], df[[respo]])) +
        geom_point(size = 2) + 
        labs(title = metrica) +
        geom_abline(intercept = 0, slope = 1) +
        theme_bw()
        print(p1)
        
    }
    
    if (isTRUE(taxa)) {
        ggfun(xvar = "Morphospecies")
        ggfun(xvar = "Genus")
        model1 <- lm(Species ~ Morphospecies, data = df2)
        model2 <- lm(Species ~ Genus, data = df2)
        models <- list(Morphospecies = model1, Genus = model2)
    } else {
        ggfun(xvar = "Transects")
        ggfun(xvar = "TransFocal") 
        model1 <- lm(TransFocalObs ~ Transects, data = df2)
        model2 <- lm(TransFocalObs ~ TransFocal, data = df2)
        models <- list(Transects = model1, TransFocal = model2)
        
    }
    
    return(models)

}

```


```{r}
sampling.results <- lapply(metrics, compare_methods, df = sampling.comparison, taxa = FALSE)
names(sampling.results) <- metrics

library(broom)
lapply(unlist(sampling.results, recursive = FALSE, use.names = TRUE), tidy)
lapply(unlist(sampling.results, recursive = FALSE, use.names = TRUE), glance)
```

```{r}
taxa.results <- lapply(metrics, compare_methods, df = taxa.comparison, taxa = TRUE)
names(taxa.results) <- metrics

library(broom)
lapply(unlist(taxa.results, recursive = FALSE, use.names = TRUE), tidy)
lapply(unlist(taxa.results, recursive = FALSE, use.names = TRUE), glance)
```




